language: cpp
compiler:
  #  - gcc
  - clang
before_install:
  - sudo add-apt-repository --yes ppa:ubuntu-toolchain-r/test
  - sudo apt-get -qq update
install:
  - sudo apt-get -qq install rake bison git gperf g++-4.8 libev-dev libevent-dev libjansson-dev libjemalloc-dev libxml2-dev libssl-dev zlib1g-dev libc-ares-dev
  - if [ "$CXX" = "g++" ]; then export CXX="g++-4.8"; fi
  - git clone https://github.com/h2o/qrintf.git
  - cd qrintf
  - sudo make install PREFIX=/usr/local
  - cd ..
script:
  - make
  - sudo make install INSTALL_PREFIX=/usr/local/trusterd
  - sudo /usr/local/trusterd/bin/trusterd conf/example/trusterd.conf.callbacks.example.rb &
  - ./mruby/build/host/mrbgems/mruby-http2/nghttp2/src/nghttp -v http://127.0.0.1:8080/index.html
  - ./mruby/build/host/mrbgems/mruby-http2/nghttp2/src/nghttp -v http://127.0.0.1:8080/index.php
  - ./mruby/build/host/mrbgems/mruby-http2/nghttp2/src/nghttp -v http://127.0.0.1:8080/index.cgi
  - ./mruby/build/host/mrbgems/mruby-http2/nghttp2/src/nghttp -v http://127.0.0.1:8080/hello
  - ./mruby/build/host/mrbgems/mruby-http2/nghttp2/src/nghttp -v http://127.0.0.1:8080/hello.rb
  - echo -n "post data dayo" > post_data
  - ./mruby/build/host/mrbgems/mruby-http2/nghttp2/src/nghttp -v http://127.0.0.1:8080/index.html -d post_data

